# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
defaults: &defaults
  docker: 
      -  image: circleci/node:13.8.0
jobs:
  build:
    <<: *defaults
    steps:
      -  run: npm run lint
  test:
     <<: *defaults
     steps:
      -  run: npm run test
  analyse:
     <<: *defaults
     steps:
      -  run: npm audit
      -  run:
           command: echo "job failed"
           when: on_fail
workflows:
  my_workflow:
    jobs:
      -  build
      -  test:
           requires:
             -  build
      -  analyse:
           requires:
             -  test