# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
defaults: &defaults
  docker: 
      -  image: amazon/aws-cli
commands:
  to_checkout:
    description: "to checkout the code"
    steps:
      -  checkout
jobs:
  build:
    <<: *defaults
    steps:
      -  to_checkout
      -  run: npm i
      -  run: npm run lint
  test:
     <<: *defaults
     steps:
      -  to_checkout
      -  run: npm i
      -  run: npm run test
  analyse:
     <<: *defaults
     steps:
      -  to_checkout
      -  run: npm audit
      -  run:
           command: echo "job failed"
           when: on_fail
  create_infrastructure:
    docker: 
      -  image: circleci/node:13.8.0
    steps:
      - checkout
      - run: 
          name: Ensure backend infrastructure exist
          command: |
            aws cloudformation deploy \
                --template-file check1.yml \
                --stack-name mynewstack

workflows:
  my_workflow:
    jobs:
      -  create_infrastructure
     # -  build
     #-  test:
     #      requires:
     #        -  build
     # -  analyse:
     #      requires:
     #        -  test