# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
defaults: &defaults
  docker: 
      -  image: amazon/aws-cli
commands:
  to_checkout:
    description: "to checkout the code"
    steps:
      -  checkout
  destroy_environment: 
    steps:
      - run:
          name: Rollback network resources
          command: |
            aws cloudformation delete-stack --stack-name prod-${CIRCLE_WORKFLOW_ID}
          when: on_fail
jobs:
  build:
    <<: *defaults
    steps:
      -  to_checkout
      -  run: npm i
      -  run: npm run lint
  test:
     <<: *defaults
     steps:
      -  to_checkout
      -  run: npm i
      -  run: npm run test
  analyse:
     <<: *defaults
     steps:
      -  to_checkout
      -  run: npm audit
      -  run:
           command: echo "job failed"
           when: on_fail
  create_infrastructure:
    docker: 
      -  image: amazon/aws-cli
    steps:
      - checkout
      - run: 
          name: Ensure backend infrastructure exist
          command: |
            aws cloudformation deploy \
                --template-file template.yml \
                --stack-name prod-${CIRCLE_WORKFLOW_ID}
      - run: return 1
      - destroy_environment
  configure_infrastructure:
    docker: 
      -  image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - 2d:e3:43:7c:dc:0e:c9:ed:1f:21:34:0e:d8:5a:c9:55
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible
      - run:
          name: verify ansible hosts
          command: |
            ansible all --list-hosts
      - run:
          name: Configure server
          command: |
            ansible-playbook -i inventory playbook.yml
  smoke_test:
    docker:
        - image: alpine:latest
    steps:
      - run: apk add --update curl
      - run:
          name: smoke test
          command: |
            URL="https://blog.udacity.com/"
            if curl -s --head ${URL} # test if blog.udacity. com exists
            then
              return 0
            else
              return 1
            fi  
  create_and_deploy_front_end:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: |
          aws cloudformation deploy \
          --template-file bucket.yml \
          --stack-name "${CIRCLE_WORKFLOW_ID:0:7}" \
          --parameter-overrides PipelineID="${CIRCLE_WORKFLOW_ID:0:7}"
      - run: |
          aws s3 sync . s3://"${CIRCLE_WORKFLOW_ID}" --delete

  get_last_deployment_id:
    steps:
      name: Add back-end ip to ansible inventory
          command: |
      -   run: |
          aws cloudformation \
            list-exports --query "Exports[?Name==\`PipelineID\`].Value" \
            --no-paginate --output text  >> ~/output.txt
          cat ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt

  promote_to_production:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: |
          aws cloudformation deploy \
            --template-file cloudfront.yml \
            --stack-name production-distro \
            --parameter-overrides PipelineID="${CIRCLE_WORKFLOW_ID}"
    
  clean_up_old_front_end:
    steps:
      - checkout
      - run: |
          aws s3 rm "s3://${OldPipelineID}" --recursive
          aws cloudformation delete-stack --stack-name "${PreviousPipelineID}"
      - attach_workspace:
          at: ~/
workflows:
  my_workflow:
    jobs:
      -  create_and_deploy_front_end
      -  promote_to_production
           requires: [create_and_deploy_front_end]
      #-  create_infrastructure
      #-  configure_infrastructure
      #-  smoke_test

     # -  build
     #-  test:
     #      requires:
     #        -  build
     # -  analyse:
     #      requires:
     #        -  test
